exclude:
 - README.md
 - Makefile
 - notebooks/nb-markdown.tpl
 - notebooks/Makefile
 - assets/fonts/lato/bower.json
 - assets/fonts/lato/index.html
 - assets/fonts/lato/*.css
 - assets/fonts/lato/*.md
 - assets/fonts/lato/*.scss
permalink: /blag/:year/:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
    style: compressed
